[default]
sqlalchemy_database_uri = 'postgresql:///dnd_site'
sqlalchemy_track_modifications = false
non_srd_roles = 49
admin_role = 99
[production]
[development]
[testing]
sqlalchemy_database_uri = 'postgresql:///dnd_site_test'