"""srd columns

Revision ID: 0cb6bd1bc1a9
Revises: 6f4f02981777
Create Date: 2021-06-04 10:25:57.744649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb6bd1bc1a9'
down_revision = '6f4f02981777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('srd', sa.Boolean(), nullable=True))
    op.add_column('spells', sa.Column('srd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'srd')
    op.drop_column('creatures', 'srd')
    # ### end Alembic commands ###
