"""case insensitive username and email

Revision ID: 0e8b5fcf6ceb
Revises: 5aa498abbb7a
Create Date: 2021-06-09 16:14:03.353061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8b5fcf6ceb'
down_revision = '5aa498abbb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###
    op.create_index('ix_users_username', 'users', [sa.text('lower(username)')])
    op.create_index('ix_users_email', 'users', [sa.text('lower(email)')])


def downgrade():
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
