"""pic non null constraint

Revision ID: 5aa498abbb7a
Revises: 7c88253a4f67
Create Date: 2021-06-08 10:29:40.488117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa498abbb7a'
down_revision = '7c88253a4f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture_path',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture_path',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
    # ### end Alembic commands ###
