"""creatures table

Revision ID: 6008004b898b
Revises: 
Create Date: 2021-06-01 15:23:17.090301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6008004b898b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=31)), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_string', sa.String(length=7), nullable=False),
    sa.Column('school', sa.String(length=15), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('casting_time', sa.String(length=127), nullable=False),
    sa.Column('range', sa.String(length=63), nullable=False),
    sa.Column('components', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('at_higher_levels', sa.Text(), nullable=True),
    sa.Column('url_path', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_path')
    )
    op.create_index(op.f('ix_spells_name'), 'creatures', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spells_name'), table_name='creatures')
    op.drop_table('creatures')
    # ### end Alembic commands ###
