"""creatures table

Revision ID: 67450550ae3c
Revises: 934d52b4b803
Create Date: 2021-06-03 10:46:47.337138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67450550ae3c'
down_revision = '934d52b4b803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=63)), nullable=False),
    sa.Column('size', sa.String(length=15), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('sub_kind', sa.String(length=31), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('armor_type', sa.String(length=63), nullable=True),
    sa.Column('hit_points', sa.String(length=63), nullable=False),
    sa.Column('hit_dice', sa.String(length=15), nullable=True),
    sa.Column('speed', sa.String(length=63), nullable=False),
    sa.Column('str', sa.Integer(), nullable=False),
    sa.Column('str_mod', sa.Integer(), nullable=False),
    sa.Column('dex', sa.Integer(), nullable=False),
    sa.Column('dex_mod', sa.Integer(), nullable=False),
    sa.Column('con', sa.Integer(), nullable=False),
    sa.Column('con_mod', sa.Integer(), nullable=False),
    sa.Column('int', sa.Integer(), nullable=False),
    sa.Column('int_mod', sa.Integer(), nullable=False),
    sa.Column('wis', sa.Integer(), nullable=False),
    sa.Column('wis_mod', sa.Integer(), nullable=False),
    sa.Column('cha', sa.Integer(), nullable=False),
    sa.Column('cha_mod', sa.Integer(), nullable=False),
    sa.Column('saving_throws', sa.String(length=63), nullable=True),
    sa.Column('damage_resistances', sa.String(length=255), nullable=True),
    sa.Column('damage_immunities', sa.String(length=255), nullable=True),
    sa.Column('condition_immunities', sa.String(length=255), nullable=True),
    sa.Column('damage_vulnerabilities', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.String(length=255), nullable=True),
    sa.Column('senses', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('challenge_rating', sa.String(length=3), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=63), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url_path', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatures_name'), 'creatures', ['name'], unique=True)
    op.create_index(op.f('ix_creatures_url_path'), 'creatures', ['url_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creatures_url_path'), table_name='creatures')
    op.drop_index(op.f('ix_creatures_name'), table_name='creatures')
    op.drop_table('creatures')
    # ### end Alembic commands ###
