"""cr redo

Revision ID: 6f4f02981777
Revises: 9d666863cd53
Create Date: 2021-06-03 11:04:49.283934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4f02981777'
down_revision = '9d666863cd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('cr_string', sa.String(length=3), nullable=False))
    op.add_column('creatures', sa.Column('cr', sa.Float(), nullable=False))
    op.drop_column('creatures', 'challenge_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('challenge_rating', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_column('creatures', 'cr')
    op.drop_column('creatures', 'cr_string')
    # ### end Alembic commands ###
