"""user profile pics

Revision ID: 7c88253a4f67
Revises: d26226ad1b22
Create Date: 2021-06-08 10:26:28.790915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c88253a4f67'
down_revision = 'd26226ad1b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_path', sa.String(length=127), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_path')
    # ### end Alembic commands ###
