"""creatures alignment

Revision ID: 9d666863cd53
Revises: 67450550ae3c
Create Date: 2021-06-03 10:49:25.502527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d666863cd53'
down_revision = '67450550ae3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('alignment', sa.String(length=31), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creatures', 'alignment')
    # ### end Alembic commands ###
