"""description html

Revision ID: af7fb4c6c12f
Revises: 6008004b898b
Create Date: 2021-06-01 15:55:05.430157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7fb4c6c12f'
down_revision = '6008004b898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatures', sa.Column('description_html', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creatures', 'description_html')
    # ### end Alembic commands ###
