"""Add tag tables for creatures and spells

Revision ID: e1a30fabfa7f
Revises: d40e31f7c5de
Create Date: 2021-12-16 08:25:10.852281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a30fabfa7f'
down_revision = 'd40e31f7c5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creature_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('spell_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('creature_tag_links',
    sa.Column('creature_id', sa.Integer(), nullable=True),
    sa.Column('creature_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creature_id'], ['creatures.id'], ),
    sa.ForeignKeyConstraint(['creature_tag_id'], ['creature_tags.id'], )
    )
    op.create_table('spell_tag_links',
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.Column('spell_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.ForeignKeyConstraint(['spell_tag_id'], ['spell_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell_tag_links')
    op.drop_table('creature_tag_links')
    op.drop_table('spell_tags')
    op.drop_table('creature_tags')
    # ### end Alembic commands ###
